# configs/collect/base.yaml
tasks: [dmc_cheetah_run, atari_pong]
num_envs_per_task: 4
n_episodes_per_task: 100

policy: random  # random | agent
agent_ckpt: null

out_data_dir: ./data/collected/demos
out_frames_dir: ./data/collected/frames
shard_size: 2048
img_size: 128
save_preview_video: false
preview_video_max_frames: 300
preview_video_fps: 20
out_videos_dir: ./data/collected/videos
